# Generated by Django 3.2 on 2021-05-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('bags', 'Bags'), ('shoes', 'Shoes'), ('glasses', 'Glasses'), ('scarves', 'Scarves'), ('gloves', 'Gloves')], max_length=10)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pictures')),
            ],
        ),
    ]
